[theme]
base                     = "dark"
primaryColor             = "#00e5a0"
backgroundColor          = "#040d1f"
secondaryBackgroundColor = "#060f2a"
textColor                = "#eef2f7"

[server]
enableStaticServing = true
